# Generated by Django 2.2 on 2022-10-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_product_tempprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempprofile',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='tempprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='TempProfile',
        ),
    ]
