# Generated by Django 2.2 on 2022-10-04 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_images/default_profile.png', upload_to='profile_images')),
                ('bio', models.CharField(default='bio', max_length=3000)),
                ('birthdate', models.DateField(default=django.utils.timezone.now)),
                ('address', models.CharField(default='address', max_length=200)),
                ('link1', models.URLField()),
                ('link2', models.URLField()),
                ('link3', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
