# Generated by Django 2.2 on 2022-10-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20221005_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='address_line1',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_line2',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=None, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link1',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link2',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link3',
            field=models.URLField(default=None, null=True),
        ),
    ]
