# Generated by Django 2.2 on 2022-10-04 16:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('course_num', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('course_name', models.CharField(max_length=100)),
                ('meeting_days', models.TextField()),
                ('meeting_start_time', models.TimeField(default='12:00')),
                ('meeting_end_time', models.TimeField(default='12:00')),
                ('meeting_location', models.CharField(max_length=25)),
                ('credit_hours', models.PositiveSmallIntegerField(default=3)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
