# Generated by Django 2.2 on 2022-10-04 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_num',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='meeting_days',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='meeting_end_time',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='course',
            name='meeting_location',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='course',
            name='meeting_start_time',
            field=models.TimeField(default='12:00'),
        ),
    ]
