# Generated by Django 2.2 on 2022-10-05 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0002_auto_20221004_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('due_date', models.DateTimeField()),
                ('points', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('t', 'Text entry'), ('f', 'File upload')], max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.Course')),
            ],
        ),
    ]
