# Generated by Django 4.1.1 on 2022-10-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0003_alter_course_id'),
        ('course_management', '0003_assignment'),
    ]

    operations = [
    ]
