# Generated by Django 2.2 on 2022-10-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0004_alter_assignment_course'),
        ('course_management', '0004_filesubmission_textsubmission'),
    ]

    operations = [
    ]
