# Generated by Django 2.2 on 2022-10-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0004_filesubmission_textsubmission'),
        ('course_management', '0004_alter_assignment_course'),
    ]

    operations = [
    ]
