# Generated by Django 2.2 on 2022-10-17 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_management', '0006_auto_20221017_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='filesubmission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='filesubmission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='filesubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='filesubmission',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='textsubmission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='textsubmission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='textsubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='textsubmission',
            name='submitted_at',
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='filesubmission',
            name='submission_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course_management.Submission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textsubmission',
            name='submission_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course_management.Submission'),
            preserve_default=False,
        ),
    ]
