# Generated by Django 2.2 on 2022-10-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0008_auto_20221017_1828'),
        ('course_management', '0005_merge_20221018_1900'),
    ]

    operations = [
    ]
