# Generated by Django 2.2 on 2022-10-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0010_course_grade_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade_scale',
            field=models.CharField(default='A>=93 it=4', max_length=15),
        ),
    ]
