# Generated by Django 2.2 on 2022-09-19 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=4)),
                ('coursenum', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('coursename', models.CharField(max_length=100)),
                ('instname', models.CharField(max_length=20)),
                ('meetingtime', models.CharField(max_length=25)),
            ],
        ),
    ]
